options:
  logging: CLOUD_LOGGING_ONLY

steps:

- name: hashicorp/terraform:latest
  entrypoint: sh
  args:
    - -c
    - |
      cd Terraform

      terraform init

      terraform validate

      terraform plan -var-file=dev.tfvars