options:
  logging: CLOUD_LOGGING_ONLY

steps:

- name: hashicorp/terraform:latest
  entrypoint: sh
  args:
    - -c
    - |
      cd Terraform

      terraform init \
        -backend-config="bucket=bucket280926-tfstate" \
        -backend-config="prefix=dev"

      terraform validate

      terraform plan -var-file=dev.tfvars

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -c
    - |
      echo "Déploiement du DAG dans Cloud Composer..."

      gsutil cp \
      dags/clientstreamdemodag.py \
      gs://europe-west1-composer-demo-ee40f67f-bucket/dags/
      
      
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -c
    - |
      echo "Déploiement du script Dataflow..."

      gsutil cp \
      dataflow/client_stream_demo.py \
      gs://bucket280926-demo-dev/dataflow/
